### ISSUE TITLE
Merge with https://github.com/evmorov/next-line-comment

### ISSUE THREAD

**Issue by bean5** [mark-hahn/comment-down#2]
You and https://github.com/evmorov/next-line-comment should get together and merge the best of both packages. It looks like you have more downloads according to the Atom UI, so maybe you already have everything you need.

**Comment by mark-hahn** [comment]
See my comments on the next-line-comment repo.

**Comment by bean5** [comment]
Cool. Glad you guys are communicating. I did see that they seemed to be similar and I couldn't tell what actual differences existed. I don't like it when people make projects that don't need to exist. But perhaps in this case you just both tackled a legitimate need concurrently. In any case, I wish you the best. Thanks for contributing.

**Comment by mark-hahn** [comment]
Of course the obvious correct solution is for core to handle comments
correctly.  Oh well...

**Comment by bean5** [comment]
That would be nice.

**Comment by bean5** [comment]
They could adopt your package into core, perhaps....especially if it was obviously better than the competitor and used by thousands.
